language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - npm install && npm install coveralls mocha-lcov-reporter --save-dev
script:
  - npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls
notifications:
  email:
    on_success: never
    on_failure: always
